### ISSUE TITLE
ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by janinebalangue** [HiDeoo/.github#7] opened 2023-10-27 03:23 UTC
### Describe the bug

I am not totally sure if this is a bug or a version error however, the module cannot be found whenever I start the project on my local machine.

I already installed **Intro.js**, then as recommended I need to install **react-intro.js** to make it more work smoothly in a react project, however, version 1.0.0 is displaying errors whenever I open/refresh the project on my local machine. Please see the attached screenshots for reference.
![image](https://github.com/HiDeoo/.github/assets/149121230/2ead2bf0-3a4a-4334-8443-b9fb3c62fe70)

### To Reproduce

1. Install Intro.js (currently installed 7.2.0)
2. Install Intro.js-react (currently installed 1.0.0)
3. Next.js version v12.3.4
4. NPM version 9.7.2

### Expected behavior

Using this library I should be able to make the onboarding work just like the ones in the demo of this library

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment] 2023-10-27 08:31
Thanks for your report.

I think this may not be the proper repository for this issue as this seems to be a problem with `intro.js-react`.

As you can see on this [Stackblitz repro](https://stackblitz.com/edit/stackblitz-starters-awf57k?file=app%2Fpage.tsx), I did not manage to reproduce the issue. Maybe this demo can help you figure out the issue in your case.

I am going to close this issue as this is not related to this repository but feel free to open a new one in the proper repository including a reproducible demo of the issue.

**Closed as completed by HiDeoo** 2023-10-27 08:31 UTC
